### PR TITLE
Avoid Code Duplication: Reuse Sleep from ThreadMonitor

### PR DESCRIPTION
**Pull request by DaGeRe**
It makes no sense to duplicate code, like the sleep method, just to keep the interface private.

### CODE REVIEW

**Comment by kinow** [comment]
Hi @DaGeRe !

Agree that code duplication is bad. But the change could perhaps be changed a little bit to make it easier to accept it in my opinion.

In `ThreadMonitor`, when you make it public, it also means that we are telling users that they are free to use this class in their code as well. Instead of it being hidden in the package level (which doesn't necessarily stops them, but discourages and at least raises the question of whether they should use it).

But I agree with the remaining changes (except by one incorrect indentation that may raise a checkstyle issue).

Would you like to try, perhaps, creating a test class in the same package, but under the test sources? That way you can either wrap or extend the origin `ThreadMonitor` and still remove the duplication in the `sleep` method. Also making it easier for us to maintain the code :-)

Cheers
Bruno

**Comment by garydgregory** [comment]
> Hi @DaGeRe !
> 
> Agree that code duplication is bad. But the change could perhaps be changed a little bit to make it easier to accept it in my opinion.
> 
> In `ThreadMonitor`, when you make it public, it also means that we are telling users that they are free to use this class in their code as well. Instead of it being hidden in the package level (which doesn't necessarily stops them, but discourages and at least raises the question of whether they should use it).
> 
> But I agree with the remaining changes (except by one incorrect indentation that may raise a checkstyle issue).
> 
> Would you like to try, perhaps, creating a test class in the same package, but under the test sources? That way you can either wrap or extend the origin `ThreadMonitor` and still remove the duplication in the `sleep` method. Also making it easier for us to maintain the code :-)
> 
> Cheers
> Bruno

Right, this class should stay package private.
You can either subclass it in the test tree as a public class or provide a public test method that accesses the package private one.

**Comment by garydgregory** [comment]
I've made simpler changes. Please see git master.

**Comment by garydgregory** [comment]
@DaGeRe ping?

**Pull request closed without merging**
