### PR TITLE
IO-170: Scalable Iterator for files, better than FileUtils.iterateFiles

### PR DESCRIPTION
**Pull request by detinho**
I took an aproach of implementing a separate class with the iterator logic.
While this brings a little code duplication, it leads to a more scalable approach, as the iterator class processes only the necessary files and directories to return the next file.

### CODE REVIEW

**Comment by garydgregory** [comment]
Why would we one these "old" APIs instead of java.nio.file.Files.walk(Path, int, FileVisitOption...) and friends? Should our Javadocs be updated instead?

**Comment by detinho** [comment]
@garydgregory in that case it would be Files.walkTree, as Files.walk was introduced on Java 1.8.
Regarding Files.walkTree, it would be possible to use it instead FileUtils.iterateFiles, but not with an Iterator pattern.
I think it would be nice to update the documentation too, so users can be aware of Files.walk in case they are using Java 1.8 already and use the Stream pattern, what do you think?

**Comment by garydgregory** [comment]
Hi @detinho 
This code is likely obsolete due to (1) the git master rework that uses Java NIO's streaming APIs and (2) this code does not use NIO streaming APIs.
May you please review git master, comment and/or update/close this PR?
TY!

**Comment by garydgregory** [comment]
Closing, see my previous comment.

**Pull request closed without merging**
