### PR TITLE
Update BoundedReader.java

### PR DESCRIPTION
**Pull request by zhanhb**
Bug, the return value should be -1 when get the end of the reader
https://docs.oracle.com/javase/8/docs/api/java/io/Reader.html

### CODE REVIEW

**Comment by krosenvold** [comment]
Can you add a testcase to BoundedReaderTest ?

**Comment by zhanhb** [comment]
OK, wait a moment

**Comment by zhanhb** [comment]
I have finished the work.

**Comment by krosenvold** [comment]
Merged, thanks ! Please close pull request

**Pull request closed without merging**
