### PR TITLE
[IO-808] non writeable destinations are I/O errors

### PR DESCRIPTION
**Pull request by elharo**
No API changes. No existing tests failed. I added a new test for this. @garydgregory

### CODE REVIEW

**Comment by garydgregory** [comment]
A question is whether we should even check for writable attributes before we write. There comments from time to time that our APIs are (obviously IMO) non-atomic, and these checks make the code fail faster but also risk of being out of sync with the underlying file system.

**Comment by elharo** [comment]
This PR seems unlikely to require source changes by users. These methods can already throw IOExceptions and those need to be handled. The only potential problem, and it's not a likely one, is if someone has a separate IllegalArgumentException catch block with special logic to handle read only files. In that case they'd need to move that logic into a block that catches IOException. However, I think more users are likely to be helped by combining IOException into a single exception type.

As to simply removing the writeable check completely, that's a definite maybe. It would simplify the code, and simplify the happy path where there's no problem with read-only files. Public API remains the same. It's a very good point that this risks being out of sync with the fiel system by the time we write. Should I go ahead and remove the requireCanWrite method?

**Comment by garydgregory** [comment]
> Should I go ahead and remove the requireCanWrite method?

I think so.

**Comment by elharo** [comment]
> > Should I go ahead and remove the requireCanWrite method?
> 
> I think so, yes.

done

**Pull request merged**
