### PR TITLE
FIX #io-697

### PR DESCRIPTION
**Pull request by richarda23**
this PR clarifies Javadoc of 2 methods to match the behaviour displayed by the code. Previously the Javadoc was ambiguous as to the expected behaviour when `size` was a value > 0 but less than the length of the InputStream.

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Thanks!

**Review by kinow — CHANGES_REQUESTED** [review]
Ah, was going to merge it when I realized the Javadocs did not build after this change. Could you take a look at the GitHub actions log output (you can click on the checks in this pr, follow the links to find the logs). It should point what failed to build. It appears to be due to "malformed HTML". Thanks!

**Comment by kinow** [comment]
Almost there! I'm re-running a failed macos job in GH actions, to see if it was some glitch in the macos build or if there's still something missing here. :+1:

**Comment by richarda23** [comment]
ok, sorry, made some heavy weather on this. all ok now

**Comment by kinow** [comment]
Thanks a lot for the initial PR and for the patience to work through the javadoc issues @richarda23 . I rebased the branch, squashed the commits down to a single commit, updated the commit message to include the JIRA issue, added the entry in `changes.xml` and merged locally. Finally, pushed to `master` :+1: JIRA Issue updated as well.

Merged, fixed. Thanks @richarda23 !!

**Pull request closed without merging**
