### PR TITLE
IO-585: Sanitize double slash after prefix

### PR DESCRIPTION
**Pull request by adammcclenaghan**
Fixes [IO-585](https://issues.apache.org/jira/browse/IO-585)

When a double slash immediately followed a prefix such as "C:\\" we would fail to merge the adjoining slashes. This change ensures that slashes of these type are merged.

### CODE REVIEW

**Comment by adammcclenaghan** [comment]
Jenkins builds are failing due to missing javadoc in a class unrelated to this change

```
[ERROR] src/main/java/org/apache/commons/io/output/NullPrintStream.java:[34,5] (javadoc) JavadocMethod: Missing a Javadoc comment.
```

**Comment by garydgregory** [comment]
I just committed the Javadoc fix.

Gary

**Comment by adammcclenaghan** [comment]
jenkins test this please

**Comment by adammcclenaghan** [comment]
Ah, seems that Jenkins hook doesn't isn't enabled for this repo - not sure how to kick off a rebuild without creating a needless commit, if someone can point me in the right direction then I'd be happy to kick off another build and see if we can get Jenkins passing on this.

**Comment by adammcclenaghan** [comment]
@garydgregory Is there anything I can do to rekick the travis build from my end?

**Comment by garydgregory** [comment]
Hi @adammcclenaghan 

You need to rebase on master to pickup changes that will allow Checkstyle to succeed where it is failing now.

**Pull request merged**
