### PR TITLE
IO-629: Providing more meaningful exceptions on file delete

### PR DESCRIPTION
**Pull request by malfist**
Applying patch found here: https://issues.apache.org/jira/browse/IO-629

### CODE REVIEW

**Comment by garydgregory** [comment]
@malfist 
Please rebase on master to allow the Travis build to proceed; this will bring in checkstyle fixes.
Gary

**Comment by malfist** [comment]
@garydgregory I think I did that, not used to working with forks.

**Comment by garydgregory** [comment]
@malfist You did the right thing. I made the fix in master after you created your PR.

**Comment by garydgregory** [comment]
I think the better path here is to add a delete API to the PathUtils class.

**Comment by malfist** [comment]
> I think the better path here is to add a delete API to the PathUtils class.

So are you thinking of moving these functions to PathUtils?
- cleanDirectory
- deleteDirectory
- deleteQuietly
- forceDelete
- forceDeleteOnExit 

For backwards compatibility, I'm assuming I should leave these functions in FileUtils, mark them as deprecated, and have them call the new PathUtils functions?

**Comment by garydgregory** [comment]
No, not quite. Nothing would move in my view. FileUtils can keep on working on File instances only and PathUtils on Path instances. It might be possible for one to delegate to the other in some cases but that is not a given.

**Comment by malfist** [comment]
I'm not following what you're asking for? Can you help me understand?

This function doesn't use Path objects except in the File.delete(Path) call. Java's Path class does not provide a mechanism to delete anything.

**Comment by garydgregory** [comment]
I think what I am saying is that we should add `PathUtils.delete()` method(s) that work from a `Path` using the `Files` API and not muck with `FileUtils`.

**Comment by garydgregory** [comment]
Please see git master for the latest.

**Comment by malfist** [comment]
Rebased and used new PathUtils.delete function

**Comment by garydgregory** [comment]
Something went wrong with your git work, master changes since your PR appear as new code here and it is now a pain to see what this PR truly provides. May you please clean up this PR?

**Comment by malfist** [comment]
> 
> 
> Something went wrong with your git work, master changes since your PR appear as new code here and it is now a pain to see what this PR truly provides. May you please clean up this PR?

Got it cleaned up

**Pull request merged**
