### PR TITLE
[IO-510] Adding ReadAHeadInputStream

### PR DESCRIPTION
**Pull request by yairzaslavsky**
Adding ReadAHeadInputStream which acts
similar to BufferedInputStream only it uses
a thread to fill in the buffer with reads
from the internal stream

### CODE REVIEW

**Comment by garydgregory** [comment]
How about allowing to pass in an ExecutorService to the ctor so that the thread can be created out of a pool.

Any thoughts about subclassing FilterInputStream?

**Comment by yairzaslavsky** [comment]
@garydgregory 
Thanks for your response.

A. Regarding to ExecutorService -  sounds like a great idea to me.
I assume you suggest using the submit method, am I correct?

B. I will try to do that -
I assume I will only need to override the read methods, am I correct?

Thanks for your review

**Comment by garydgregory** [comment]
Hi,

A) Yes, I was thinking about submit(Runnable)
B) You'll have to see what is need, I've not tried it.

Gary

**Comment by garydgregory** [comment]
Since you mentioned BufferedInputStream, note that BufferedInputStream subclasses FilteredInputStream.

**Comment by yairzaslavsky** [comment]
@garydgregory  uploaded a new PR, based on your suggestions.

**Comment by yairzaslavsky** [comment]
@garydgregory 
After I synced my fork with master, and rebased, not sure why coveralls fails.
I'm less familiar with this tool, and could not see a clear indication where my code breaks the coverage.
Any assistance on this will be helpful

Cheers,
Yair

**Comment by PascalSchumacher** [comment]
I guess there are some random elements in the test code of commons-io. The code coverage seems to vary a bit even if there are not actual changes.

You can check https://coveralls.io/builds/8959373 verify if the coverage changes are really caused by your pull request.

**Comment by yairzaslavsky** [comment]
@PascalSchumacher  - this is not what I see when I view the list of files a the  URL you provided (and I already checked that before posting the question).
At first , I did had an issue as my fork was not synchronized with the mirror of commons-io on github,

Any other tips on the issue are more than welcome :)

Thanks,
Yair

**Comment by yairzaslavsky** [comment]
@PascalSchumacher  I meant the tests for  class, or the class itself do not appear in the list of files that coveralls mentions.

**Comment by PascalSchumacher** [comment]
@yairzaslavsky to quote @bodewig from: https://github.com/apache/commons-compress/pull/12

>I think this is related to our Travis CI setup using different JDKs and Coveralls picks whichever build finishes first. For different JDKs you get slightly different coverage values.

**Comment by PascalSchumacher** [comment]
@garydgregory What do you think, is this now good to merge? Thanks!

**Comment by garydgregory** [comment]
I can look tomorrow. Note that the spelling it "ahead" as one word.

**Comment by garydgregory** [comment]
Thank you for your updated patch. May you please add Javadocs to the public methods?

**Comment by garydgregory** [comment]
Closing since `ReadAheadInputStream` is in Commons IO as of 2.9.0.

**Pull request closed without merging**
