### PR TITLE
Simplify expression

### PR DESCRIPTION
**Pull request by bhawna94**
Simplify expressions to enhance code readability.

### CODE REVIEW

**Comment by namannigam** [comment]
Looks more like formatting changes. If not, can you revert all such formatting differences to specifically point out which expression is simplified.

**Comment by sebbASF** [comment]
Whilst the operations with 0 don't actually do anything, they help to make the algorithm clearer, so I don't think the code should be changed. Or, if the code is changed, there needs to be documentation to note that the changed code is part of the same sequence.
In any case, won't the compiler optimise the operations away?

**Comment by garydgregory** [comment]
-1 Same issue as @sebbASF mentions: the code follows a pattern for obvious clarity.

**Comment by jochenw** [comment]
I would support a change, that splits the code into multiple statements. To give an idea of what I am thinking:

        byte byte0 = /* Whatever's necessary to calculate one byte */;
        byte byte1 = /* Calculate another byte */;
        byte byte2 = /* Calculate the third byte */
        byte byte3 = /* Calculate the lasr´t byte */
        long result = byte0 | (byte1 << 8) | (byte2 << 16) | (byte3 << 24);

In my opinion, that would be actually readable. The current code as well as this proposed change aren't.

**Comment by garydgregory** [comment]
Unless someone update the PR, we should close it IMO.

**Comment by garydgregory** [comment]
No feedback, closing.

**Pull request closed without merging**
