### PR TITLE
add filterReadeLines & consumerReadeLine

### PR DESCRIPTION
**Pull request by li-keguo**
add
```java
void readLines(final File file, final Charset charset, final Consumer<String> consumer);
List<String> readLines(final File file, final Charset charset, final Predicate<String> filter);
```

### CODE REVIEW

**Comment by garydgregory** [comment]
-1: no unit tests, and the build breaks.

**Comment by li-keguo** [comment]
> Hello @li-keguo Why not use Java's Files.lines() APIs instead of these?

HI @garydgregory 
It is a good idea to implement filters using Files.lines.
```java
Files.lines(file.toPath(), charset)
                    .filter(filter)
                    .collect(Collectors.toList());
```
However, this is not consumer-friendly. The stream intermediate process does not trigger execution.

**Comment by li-keguo** [comment]
Help me fix ci

**Comment by li-keguo** [comment]
ok I close

**Pull request closed without merging**
