### PR TITLE
[IO-572] Extract out replicated code in org.apache.commons.io.FileUtils

### PR DESCRIPTION
**Pull request by pranet**
Created two additional private methods which hold the replicated code.

### CODE REVIEW

**Comment by garydgregory** [comment]
This PR does not apply cleanly on top of git master ATM. Would you mind reabasing it?

**Comment by pranet** [comment]
I didn't get you sorry. Can you please help me out with that? 
From what I'm able to see, my PR is already based from upstream/master HEAD. 
Did you perhaps want me to squash the commits instead? (If yes, should I squash into 1 for all refactoring, or 2 based on the functions affected?)

**Comment by garydgregory** [comment]
My bad, the patch applies cleanly from the command line, but did not from Eclipse.

**Comment by PascalSchumacher** [comment]
@pranet Thanks! 👍 

@garydgregory merged the changes in https://github.com/apache/commons-io/commit/f0751b65cf680456557aa1bf5c56b12f5c1a0fe0

**Pull request closed without merging**
