### PR TITLE
Refactor io.monitor to support alternativ file entities

### PR DESCRIPTION
**Pull request by col-panic**
I want to combine the io.monitor with the https://github.com/hierynomus/smbj project, to realize a SMB capable io monitor. In order to achieve this, I have to replace certain hard-coded handles like File with the resp. SMBJ handles. 

To this end, I started refactoring the code so that I may realize this alternative implementation. Within my IDE i have a prototype of this combination (realized within a separate project) that basically works.

My question is: would the commons-io community care for accepting a PR that "opens-up" the monitor for alternative implementations?

The PR at hand serves as a basis for discussion.

### CODE REVIEW

**Comment by garydgregory** [comment]
May you please rebase on master?

**Comment by garydgregory** [comment]
@col-panic 
May you please rebase on master?

**Comment by col-panic** [comment]
I did a dumb rebase on the current master, only accepting the incoming changes. I did not have a look at the code, as it's been a while I haven been creating this PR and we realized a separate solution for this in the meantime! I leave it up to you what to do with it, as I can't spend time more time on this - sorry! :(

**Comment by garydgregory** [comment]
This PR now changes 463 files, obviously not good or intended I am sure. Please review rebase on git master.

**Comment by garydgregory** [comment]
Closing, no feedback and 400+ files changes is impossible to review.

**Pull request closed without merging**
