### PR TITLE
[IO-732] CharArrayWriter

### PR DESCRIPTION
**Pull request by pjfanning**
A draft implementation of https://issues.apache.org/jira/browse/IO-732.
* needs more tests
* needs better javadoc

### CODE REVIEW

**Comment by garydgregory** [comment]
@pjfanning 
Thank you for your contribution. I will look at this in the context of 2.10.0 as I am about done preparing the 2.9.0 release candidate.

**Comment by pjfanning** [comment]
@garydgregory thanks, I can update the javadocs in my PR later to say 2.10.0. My PR uses the IOUtils charArray method - would it be possible to make that public in the 2.9.0 release? Accoring the the javadoc, the charArray methods were only recently added and it might be tidier to make them public now than making them public later.

**Comment by garydgregory** [comment]
@pjfanning 
Sorry, I am in the middle of the release candidate process ATM.

**Comment by jochenw** [comment]
I'd like to see an explanation for this statement:



        It is also a good alternative to java.io.StringWriter class.

**Comment by pjfanning** [comment]
@jochenw  I guess the point is that this CharArrayWriter can also be used to generate a String but I suppose commons-io already has StringBuilderWriter and maybe that is a better choice if building a String is what you want. I can remove the line from the Javadoc - I'm neutral abut whether it is needed.

**Comment by jochenw** [comment]
The point I am trying to make: Right now, I wouldn't know when, and why, to use which? And, my guess is: If I don't know, other users won't know, either.

**Comment by garydgregory** [comment]
@jochenw May we close this PR then?

**Comment by garydgregory** [comment]
Closing per  @jochenw's comment.

**Pull request closed without merging**
