### PR TITLE
[IO-414] Don't write a BOM on every (or any) line

### PR DESCRIPTION
**Pull request by elharo**
Something very weird happened with the previous iteration of this PR. This PR should work.

### CODE REVIEW

**Comment by garydgregory** [comment]
Hi @elharo 
You can run `mvn` from a command shell to catch these build errors. `mvn` runs our default goal which includes all the checks.

**Comment by elharo** [comment]
mvn test doesn't catch checkstyle errors. I have to look for those specifically.

On the previous iteration, the CI passed on my PR. The code was somehow modified after I submitted it.

**Comment by garydgregory** [comment]
> mvn test doesn't catch checkstyle errors. I have to look for those specifically.
> 
> On the previous iteration, the CI passed on my PR. The code was somehow modified after I submitted it.

No you don't, as noted above, run `mvn`, by itself, this causes the default Maven goal to run, which includes all of the checks.

**Comment by garydgregory** [comment]
Side note: In general, don't edit `changes.xml` in PRs, this usually causes conflicts if another PR also edits that file or if, invariably, that file has been edited in the course of plain old development.

As an alternative, we could use Log4j's change log mechanism which avoids any and all conflicts.

**Pull request merged**
